name: Workflows, Jobs, and Steps Version 2

on: 
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps: 
        - run: echo "A job consists of"
        - run: echo "one or more steps"
        - run: echo "which run sequentially"
        - run: echo "within the same compute environment version 2"
  job-2:
    runs-on: ubuntu-24.04
    steps:
        - run: echo "Multiple jobs can run in parallel version 2"
  job-3:
    runs-on: ubuntu-24.04
    needs:
        - job-1
        - job-2
    steps:
        - run: echo "They can also depend on one another... version 2"
                
  job-4:
    runs-on: ubuntu-24.04
    needs:
        - job-3
        - job-2
    steps:
        - run: echo "They can also depend on one another... version 2" 